# Generated by Django 2.2 on 2020-07-30 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=256)),
                ('tracing_number', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField()),
                ('organization_id', models.CharField(blank=True, max_length=256, null=True)),
                ('expected_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=256, null=True)),
                ('receipt_id', models.CharField(blank=True, max_length=256, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete='CASCADE', to='customer.Customer')),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Failed_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_reason', models.CharField(max_length=256)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=32, null=True)),
                ('receipt_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete='CASCADE', to='contract.Contract')),
                ('payment_method', models.ForeignKey(on_delete='CASCADE', to='contract.Payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('plan_id', models.CharField(max_length=256)),
                ('quantity', models.CharField(max_length=256)),
                ('memo', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete='CASCADE', to='contract.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Failed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
                ('failed_reason', models.ForeignKey(on_delete='CASCADE', to='contract.Failed_reason')),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
                ('customer', models.ForeignKey(on_delete='CASCADE', to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Destroyed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sample_destroyed', models.BooleanField(default=1)),
                ('sample_destroyed_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete='CASCADE', to='contract.Order'),
        ),
        migrations.AddField(
            model_name='box',
            name='plan',
            field=models.ForeignKey(on_delete='CASCADE', to='product.Plan'),
        ),
    ]
