# Generated by Django 2.2 on 2020-09-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=250, unique=True, verbose_name='* 流水號')),
                ('tracing_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='宅配單號')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(verbose_name='* 簽約日期')),
                ('expected_quantity', models.PositiveIntegerField(null=True, verbose_name='* 預期數量')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Destroyed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sample_destroyed', models.BooleanField(default=1, verbose_name='* 銷毀註記')),
                ('sample_destroyed_date', models.DateField(blank=True, null=True, verbose_name='銷毀日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='DNA取回日期')),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Failed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Failed_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_reason', models.CharField(max_length=32, unique=True, verbose_name='* 失敗原因')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='訂單日期')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Order_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='商品數量')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': '該方法已經存在'}, max_length=32, unique=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file_upload', models.FileField(upload_to='file/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(null=True, verbose_name='* 開立發票日期')),
                ('receipt_number', models.CharField(max_length=32, null=True, unique=True, verbose_name='* 發票號碼')),
                ('receipt_amount', models.PositiveIntegerField(null=True, verbose_name='* 發票金額')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='入賬日期')),
                ('receipt_content', models.TextField(blank=True, null=True, verbose_name='發票內容')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='* 合約')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Payment_method', verbose_name='* 付款方式')),
            ],
        ),
    ]
