# Generated by Django 2.2 on 2020-09-23 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '__first__'),
        ('customer', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Organization', verbose_name='* 單位'),
        ),
        migrations.AddField(
            model_name='order_quantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Order', verbose_name='訂單'),
        ),
        migrations.AddField(
            model_name='order_quantity',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Plan', verbose_name='方案'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='* 合約'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ManyToManyField(to='product.Plan', verbose_name='* 方案'),
        ),
        migrations.AddField(
            model_name='failed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='* 採樣盒'),
        ),
        migrations.AddField(
            model_name='failed',
            name='failed_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Failed_reason', verbose_name='* 失敗原因'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='* 採樣盒'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='* 受測者'),
        ),
        migrations.AddField(
            model_name='destroyed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='* 檢驗盒'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='* 客戶/聯絡人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ManyToManyField(to='customer.Organization', verbose_name='* 機構/單位'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='* 負責人'),
        ),
        migrations.AddField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Order', verbose_name='* 訂單'),
        ),
        migrations.AddField(
            model_name='box',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Plan', verbose_name='* 方案'),
        ),
    ]
