# Generated by Django 2.2 on 2020-08-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ManyToManyField(to='customer.Organization'),
        ),
    ]
