# Generated by Django 2.2 on 2020-10-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='', max_length=12, verbose_name='* 訂單代號'),
        ),
    ]
