# Generated by Django 2.2 on 2020-08-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('contract', '0002_auto_20200803_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ManyToManyField(to='product.Plan'),
        ),
    ]
