# Generated by Django 2.2 on 2020-10-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_order_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='', max_length=64, verbose_name='* 訂單代號'),
        ),
    ]
