# Generated by Django 2.2 on 2020-10-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20201020_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='* 合約名稱/代號'),
        ),
    ]
