# Generated by Django 2.2 on 2020-08-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20200804_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
