# Generated by Django 2.2 on 2020-08-12 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Order'),
        ),
        migrations.AlterField(
            model_name='box',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Plan'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destroyed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='failed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box'),
        ),
        migrations.AlterField(
            model_name='failed',
            name='failed_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Failed_reason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ManyToManyField(null=True, to='product.Plan'),
        ),
        migrations.AlterField(
            model_name='order_quantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Order'),
        ),
        migrations.AlterField(
            model_name='order_quantity',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Plan'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Payment_method'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
