# Generated by Django 2.2 on 2020-08-13 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_auto_20200812_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Order', verbose_name='訂單'),
        ),
        migrations.AlterField(
            model_name='box',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Plan', verbose_name='方案'),
        ),
        migrations.AlterField(
            model_name='box',
            name='serial_number',
            field=models.CharField(max_length=250, unique=True, verbose_name='流水號'),
        ),
        migrations.AlterField(
            model_name='box',
            name='tracing_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='宅配單號'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(verbose_name='簽約日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='客戶/聯絡人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expected_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='預期數量'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='organization',
            field=models.ManyToManyField(to='customer.Organization', verbose_name='機構/單位'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='負責人'),
        ),
        migrations.AlterField(
            model_name='destroyed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='檢驗盒'),
        ),
        migrations.AlterField(
            model_name='destroyed',
            name='is_sample_destroyed',
            field=models.BooleanField(default=1, verbose_name='銷毀註記'),
        ),
        migrations.AlterField(
            model_name='destroyed',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='DNA取回公司日期'),
        ),
        migrations.AlterField(
            model_name='destroyed',
            name='sample_destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='銷毀日期'),
        ),
        migrations.AlterField(
            model_name='failed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='採樣盒'),
        ),
        migrations.AlterField(
            model_name='failed',
            name='failed_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Failed_reason', verbose_name='失敗原因'),
        ),
        migrations.AlterField(
            model_name='failed_reason',
            name='failed_reason',
            field=models.CharField(max_length=32, unique=True, verbose_name='失敗原因'),
        ),
        migrations.AlterField(
            model_name='failed_reason',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='合約'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='訂單日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ManyToManyField(null=True, to='product.Plan', verbose_name='方案'),
        ),
        migrations.AlterField(
            model_name='order_quantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Order', verbose_name='訂單'),
        ),
        migrations.AlterField(
            model_name='order_quantity',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Plan', verbose_name='方案'),
        ),
        migrations.AlterField(
            model_name='order_quantity',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='商品數量'),
        ),
        migrations.AlterField(
            model_name='payment_method',
            name='name',
            field=models.CharField(error_messages={'unique': '該方法已經存在'}, max_length=32, unique=True, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='合約'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='付款日期'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Payment_method', verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='發票金額'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='開立發票日期'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='發票號碼'),
        ),
    ]
