# Generated by Django 2.2 on 2020-08-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20200820_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ManyToManyField(to='product.Plan', verbose_name='方案'),
        ),
    ]
