# Generated by Django 2.2 on 2020-09-15 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200910_0831'),
        ('contract', '0010_auto_20200826_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_content',
            field=models.TextField(blank=True, null=True, verbose_name='發票內容'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Organization', verbose_name='* 單位'),
        ),
        migrations.AlterField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Order', verbose_name='* 訂單'),
        ),
        migrations.AlterField(
            model_name='box',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Plan', verbose_name='* 方案'),
        ),
        migrations.AlterField(
            model_name='box',
            name='serial_number',
            field=models.CharField(max_length=250, unique=True, verbose_name='* 流水號'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(verbose_name='* 簽約日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='* 客戶/聯絡人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expected_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='* 預期數量'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='organization',
            field=models.ManyToManyField(to='customer.Organization', verbose_name='* 機構/單位'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='* 負責人'),
        ),
        migrations.AlterField(
            model_name='destroyed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='* 檢驗盒'),
        ),
        migrations.AlterField(
            model_name='destroyed',
            name='is_sample_destroyed',
            field=models.BooleanField(default=1, verbose_name='* 銷毀註記'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='* 採樣盒'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='* 受測者'),
        ),
        migrations.AlterField(
            model_name='failed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='*採樣盒'),
        ),
        migrations.AlterField(
            model_name='failed',
            name='failed_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Failed_reason', verbose_name='*失敗原因'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='* 合約'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ManyToManyField(to='product.Plan', verbose_name='* 方案'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='* 合約'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='入賬日期'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Payment_method', verbose_name='* 付款方式'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_amount',
            field=models.PositiveIntegerField(null=True, verbose_name='* 發票金額'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(null=True, verbose_name='* 開立發票日期'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='* 發票號碼'),
        ),
    ]
