# Generated by Django 2.2 on 2020-09-16 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contract', '0011_auto_20200915_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failed',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Box', verbose_name='* 採樣盒'),
        ),
        migrations.AlterField(
            model_name='failed',
            name='failed_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Failed_reason', verbose_name='* 失敗原因'),
        ),
        migrations.AlterField(
            model_name='failed_reason',
            name='failed_reason',
            field=models.CharField(max_length=32, unique=True, verbose_name='* 失敗原因'),
        ),
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file_upload', models.FileField(upload_to='file/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
