# Generated by Django 2.2 on 2020-08-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
