# Generated by Django 2.2 on 2020-09-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200910_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='job',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
