# Generated by Django 2.2 on 2020-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contend_type', models.ForeignKey(on_delete='CASCADE', to='contenttypes.ContentType')),
                ('product', models.ForeignKey(on_delete='CASCADE', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.ForeignKey(on_delete='CASCADE', to='product.Prefix')),
                ('product', models.ForeignKey(on_delete='CASCADE', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete='CASCADE', to='product.Product')),
            ],
        ),
    ]
