# Generated by Django 2.2 on 2020-10-30 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20201022_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
