# Generated by Django 2.2 on 2020-08-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action_flag',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
