# Generated by Django 2.2 on 2020-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20200821_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='change_message',
            field=models.TextField(),
        ),
    ]
