# Generated by Django 2.2 on 2020-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probiotics2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_concentration', models.DecimalField(decimal_places=2, max_digits=7)),
                ('report_complete_date', models.DateField(blank=True, null=True)),
                ('report_delivery_date', models.DateField(blank=True, null=True)),
                ('probiotics_delivery_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Probiotics1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway', models.CharField(blank=True, max_length=16, null=True)),
                ('report_complete_date', models.DateField(blank=True, null=True)),
                ('report_delivery_date', models.DateField(blank=True, null=True)),
                ('probiotics_delivery_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Next_Generation_Sequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_complete_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
            ],
        ),
        migrations.CreateModel(
            name='MicrobioRx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_concentration', models.DecimalField(decimal_places=2, max_digits=7)),
                ('report_complete_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
            ],
        ),
        migrations.CreateModel(
            name='GenoHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_concentration', models.DecimalField(decimal_places=2, max_digits=7)),
                ('od_260_230', models.DecimalField(decimal_places=2, max_digits=7)),
                ('od_260_280', models.DecimalField(decimal_places=2, max_digits=7)),
                ('report_complete_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete='CASCADE', to='contract.Box')),
            ],
        ),
    ]
