# Generated by Django 2.2 on 2020-09-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genohealth',
            name='dna_concentration',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='genohealth',
            name='od_260_230',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='genohealth',
            name='od_260_280',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='microbiorx',
            name='dna_concentration',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='probiotics2',
            name='dna_concentration',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
